In [0]:
import numpy as np
from tempfile import TemporaryFile

In [0]:
mainfile= TemporaryFile()

In [0]:
import random

In [22]:
a=int(input("enter number of row"))

enter number of row3


In [23]:
b=int(input("enter number of coloum"))

enter number of coloum4


In [0]:
c=np.random.random((a,b))

In [48]:
x=np.save('mainfile',c)
print("the matrix is saved in the file mainfile.npy")

the matrix is saved in the file mainfile.npy


In [0]:
y=np.load('mainfile.npy')

In [50]:
print("your matrix is")
print(y)

your matrix is
[[0.54395365 0.01785594 0.86146842 0.00955264]
 [0.47696976 0.59684246 0.67715202 0.76576634]
 [0.57167557 0.53399953 0.03047632 0.57690718]]
