<a href="https://colab.research.google.com/github/ujjusharma/ML-prolems/blob/supervisedML/tensorflow_%26_placeholder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow
!pip3 list | grep -i tensorflow

mesh-tensorflow          0.0.5                
tensorflow               1.14.0               
tensorflow-estimator     1.14.0               
tensorflow-hub           0.4.0                
tensorflow-metadata      0.13.0               
tensorflow-probability   0.7.0                


In [0]:
import tensorflow as tf

In [0]:
x=tf.constant([30])    # single value constant   # to assign fix value in tensorflow we need to define constant 

In [0]:
# multiple value constant
x1=tf.constant([3,5,66,88]) 

In [24]:
type(x)

tensorflow.python.framework.ops.Tensor

In [25]:
y=tf.constant(20)
type(y)

tensorflow.python.framework.ops.Tensor

In [0]:
#equation
z=x+y  #  new tensor  ---z equation compile and store and wait for resources 

#cpu, gpu,tpu 

In [27]:
type(z)

tensorflow.python.framework.ops.Tensor

In [0]:
z1=tf.add(x,y)   # we have another method to add the same

In [0]:
# now time for assiging for resources to our equation 
sess=tf.Session()  # connect cpu,gpu,tpu

In [0]:
# now we can run our equation
output=sess.run(z)

In [31]:
output

array([50], dtype=int32)

In [0]:
# to closing session 
sess.close()

In [0]:
# we can perform same task in another way
with tf.Session() as sess:
  output1=sess.run(z)
  tf.summary.FileWriter(sess.graph)   # this is optional

In [40]:
output1

array([50], dtype=int32)

**PlaceHolder** **next** **line**

PlaceHolder next line

In [0]:
# first placeholder
p1=tf.placeholder(tf.int32)

In [0]:
p2=tf.placeholder(tf.int32)

In [0]:
sum=tf.add(p1,p2)    # adding values

In [0]:
sum1=p1+p2    # general

In [0]:
# time for creating session
with tf.Session() as sess:
  output2=sess.run(sum1,{p1:[3,6],p2:[5,8]})

In [50]:
output2

array([ 8, 14], dtype=int32)